pull_request_rules:


  - name: feature branch
    conditions:
      - head~=^feature/
    actions:
      label:
        add: [feature]

  - name: fix branch
    conditions:
      - head~=^fix/
    actions:
      label:
        add: [bug]


  - name: commit contains refactor
    conditions:
      - commit~= (?i)\brefactor\b
    actions:
      label:
        add: [feature]

  - name: commit contains fix
    conditions:
      - commit~= (?i)\bfix\b
    actions:
      label:
        add: [bug]

  - name: commit contains ci or build
    conditions:
      - commit~= (?i)\b(ci|build)\b
    actions:
      label:
        add: [ci]

  - name: commit contains doc
    conditions:
      - commit~= (?i)\b(doc|docs|documentation)\b
    actions:
      label:
        add: [documentation]

  - name: commit contains misc
    conditions:
      - commit~= (?i)\bmisc\b
    actions:
      label:
        add: [misc]

  - name: commit contains qwen
    conditions:
      - commit~= (?i)qwen
    actions:
      label:
        add: [qwen]

  - name: commit contains update
    conditions:
      - commit~= (?i)\bupdate\b
    actions:
      label:
        add: [update]

  - name: commit contains glm
    conditions:
      - commit~= (?i)\bglm\b
    actions:
      label:
        add: [glm]

  - name: commit contains deepseek
    conditions:
      - commit~= (?i)deepseek
    actions:
      label:
        add: [deepseek]


  - name: docs change
    conditions:
      - files~=^docs/
    actions:
      label:
        add: [documentation]